### ISSUE TITLE
issue in the right nozzle start gcode. 

### ISSUE THREAD

**Issue by reimannsum** [DrLex0/FFCP-GCodeSnippets#12]
**Describe the bug**

Small part taking 45.5 hours and using 13.8km filament

**Environment**

Windows 10, Slic3r 1.3.0, GpxUi v2.5.2

**To Reproduce**

Slicing included stl using the Right nozzle Start code found here results in the gcode (Does not work.gcode) is estimated to take 45 hours and take 13.8km of filament.
slicing using the starting gcode here https://3duniverse.org/2014/01/05/using-slic3r-flashforge-creator/ (Surger Bobbin Holder v6.gcode)is estimated to take 60 min and use 2.12m of filament, but an error is thrown
```
(line 146) warning G92 emulation unable to determine all coordinates to set via x3g:140 set extended position
current position defined as X:0.00 Y:0.00 Z:0.00 A:0.00 B:0.00
(line 146) warning G92 emulation unable to determine all coordinates to set via x3g:140 set extended position
current position defined as X:0.00 Y:0.00 Z:0.00 A:0.00 B:0.00
```
slicing with Flashprint gives an estimated print time of 42 min and also uses 2.11 m of filament (Flashprint.x3g)

if you also know why both gcode > x3g files open in flashprint showing they are centered on the corner of the bed and so would largely print off the bed of range of motion allows, I would apricate that but that is not the issue at hand

[Tests.zip](https://github.com/DrLex0/FFCP-GCodeSnippets/files/5824559/Tests.zip)

**Comment by DrLex0** [comment]
The gcode files show that you are using Slic3r and not PrusaSlicer. I do not offer support for using these files with Slic3r, I have now made this a bit more explicit in the README. Try going through the  PrusaSlicer instead and get back if you still have issues.

(The gcode files also show that your print bed size is wrong, which is either caused by Slic3r not being entirely compatible with the PrusaSlicer ini files, or you having not followed all instructions. This would explain why your prints do not end up where you expect them, although I don't know where you expected them with the preview clearly showing a square bed shape.)
